config/routes.rb
Shaolin::Application.routes.draw do

  post "users/:user_id/give_points/:lesson_id" => "users#give_points"

  get "execution/execute"

  get "execution/match"
  match "lessons/take/:id" => "lessons#take"

  resources :sessions
  resources :users
  resources :lessons
  resources :paragraphs
  resources :tasks

  resources :languages
  match "language/compile" => "execution#execute"

  

  
  root :to => 'home#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :lesson
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /task
  # GET /task.json
  def index
    @tasks = Task.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :ok }
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.slim
= form_for @task do |f|
  -if @task.errors.any?
    #error_explanation
      h2 = "#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
      ul
        - @task.errors.full_messages.each do |msg|
          li= msg

  .field
    = f.label :initial_code
    = f.text_area :initial_code, :style => "height: 5em;"
  .field
    = f.label :expected
    = f.text_field :expected
  .field
    = f.label :hint
    = f.text_field :hint
  .field
    = f.label :position
    = f.number_field :position
  .field
    = f.label :lesson_id
    = f.select 'lesson_id', options_from_collection_for_select(Lesson.all, "id", "title")
  .actions
    = f.submit 'Save', class: "ui-button ui-widget"

app/views/tasks/edit.html.slim
h1 Editing task

== render 'form'

= link_to 'Show', @task
'|
= link_to 'Back', lesson_tasks_path

app/views/tasks/index.html.slim
h1 Listing tasks

table.list-table
  tr
    th.ui-corner-tl Input
    th Output
    th Expectation
    th Lesson
    th Position
    th
    th
    th.ui-corner-tr

  - @tasks.each do |task|
    tr
      td= task.initial_code
      td= task.expected
      td= task.hint
      td= link_to task.lesson.title, lesson_path(task.lesson)
      td= task.position
      td= link_to 'Show', task
      td= link_to 'Edit', edit_task_path(task)
      td= link_to 'Destroy', task, :confirm => 'Are you sure?', :method => :delete

br

button.ui-button.ui-widget
  = link_to 'New Task', new_task_path, class: "ui-button-text-only"

app/views/tasks/new.html.slim
h1 New task

== render 'form'

button.ui-button.ui-widget
  = link_to 'Back', tasks_path, class: "ui-button-text-only"

app/views/tasks/show.html.slim
p#notice = notice

p
  b Input:
  = @task.initial_code
p
  b Output:
  = @task.expected
p
  b Expectation:
  = @task.hint
p
  b Position:
  = @task.position
p
  b Lesson:
  = link_to @task.lesson.title, lesson_path(@task.lesson)

= link_to 'Edit', edit_task_path(@task)
'|
= link_to 'Back', tasks_path