config/routes.rb
Shaolin::Application.routes.draw do

  post "users/:user_id/give_points/:lesson_id" => "users#give_points"

  get "execution/execute"

  get "execution/match"
  match "lessons/take/:id" => "lessons#take"

  resources :sessions
  resources :users
  resources :lessons
  resources :paragraphs
  resources :tasks

  resources :languages
  match "language/compile" => "execution#execute"

  

  
  root :to => 'home#index'

end

app/models/language.rb
class Language < ActiveRecord::Base
  has_many :lessons
  validates_presence_of :name, :command, :file_extension
  validates_format_of :command, :with => /%{source_file}/
  validates_format_of :wrapping_code, :with => /%{user_input}/
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_filter :require_admin
  # GET /languages
  # GET /languages.json
  def index
    @languages = Language.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @languages }
    end
  end
     
  # GET /languages/1
  # GET /languages/1.json
  def show
    @language = Language.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @language }
    end
  end

  # GET /languages/new
  # GET /languages/new.json
  def new
    @language = Language.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @language }
    end
  end

  # GET /languages/1/edit
  def edit
    @language = Language.find(params[:id])
  end

  # POST /languages
  # POST /languages.json
  def create
    @language = Language.new(params[:language])

    respond_to do |format|
      if @language.save
        format.html { redirect_to @language, notice: 'Language was successfully created.' }
        format.json { render json: @language, status: :created, location: @language }
      else
        format.html { render action: "new" }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /languages/1
  # PUT /languages/1.json
  def update
    @language = Language.find(params[:id])

    respond_to do |format|
      if @language.update_attributes(params[:language])
        format.html { redirect_to @language, notice: 'Language was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /languages/1
  # DELETE /languages/1.json
  def destroy
    @language = Language.find(params[:id])
    @language.destroy

    respond_to do |format|
      format.html { redirect_to languages_url }
      format.json { head :ok }
    end
  end
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/views/languages/_form.html.slim
= form_for @language do |f|
  -if @language.errors.any?
    #error_explanation
      h2 = "#{pluralize(@language.errors.count, "error")} prohibited this language from being saved:"
      ul
        - @language.errors.full_messages.each do |msg|
          li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :command
    = f.text_field :command
  .field
    = f.label :file_extension
    = f.text_field :file_extension
  .field
    = f.label :wrapping_code
    = f.text_area :wrapping_code
  .actions
    = f.submit 'Save', class: "ui-button ui-widget"

app/views/languages/edit.html.slim
h1 Editing language

== render 'form'

= link_to 'Show', @language
'|
= link_to 'Back', languages_path

app/views/languages/index.html.slim
h1 Listing languages

table.list-table
  tr
    th.ui-corner-tl Name
    th Description
    th Command
    th File extension
    th Wrapping code
    th
    th
    th.ui-corner-tr

  - @languages.each do |language|
    tr
      td= language.name
      td= language.description
      td= language.command
      td= language.file_extension
      td= language.wrapping_code
      td= link_to 'Show', language
      td= link_to 'Edit', edit_language_path(language)
      td= link_to 'Destroy', language, :confirm => 'Are you sure?', :method => :delete

br

button.ui-button.ui-widget
  = link_to 'New Language', new_language_path, class: "ui-button-text-only"

app/views/languages/new.html.slim
h1 New language

== render 'form'

button.ui-button.ui-widget
  = link_to 'Back', languages_path, class: "ui-button-text-only"

app/views/languages/show.html.slim
p#notice = notice

p
  b Name:
  = @language.name
p
  b Description:
  = @language.description
p
  b Command:
  = @language.command
p
  b File extension:
  = @language.file_extension
p
  b Wrapping code:
  = @language.wrapping_code

button.ui-button.ui-widget
  = link_to 'Edit', edit_language_path(@language), class: "ui-button-text-only"
button.ui-button.ui-widget
  = link_to 'Back', languages_path, class: "ui-button-text-only"