config/routes.rb
Shaolin::Application.routes.draw do

  post "users/:user_id/give_points/:lesson_id" => "users#give_points"

  get "execution/execute"

  get "execution/match"
  match "lessons/take/:id" => "lessons#take"

  resources :sessions
  resources :users
  resources :lessons
  resources :paragraphs
  resources :tasks

  resources :languages
  match "language/compile" => "execution#execute"

  

  
  root :to => 'home#index'

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :language
  validates_presence_of :language
  
  has_many :paragraphs
  has_many :tasks

  def components
    (paragraphs + tasks).sort { |component1, component2| component1.position <=> component2.position }
  end

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_filter :require_admin, :except => [:take, :index]
  before_filter :require_login, :only => [:index]

  def take
    @lesson = Lesson.find params[:id]  
  end

  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lessons }
    end
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
    @lesson = Lesson.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lesson }
    end
  end

  # GET /lessons/new
  # GET /lessons/new.json
  def new
    @lesson = Lesson.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lesson }
    end
  end

  # GET /lessons/1/edit
  def edit
    @lesson = Lesson.find(params[:id])
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(params[:lesson])

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render json: @lesson, status: :created, location: @lesson }
      else
        format.html { render action: "new" }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lessons/1
  # PUT /lessons/1.json
  def update
    @lesson = Lesson.find(params[:id])

    respond_to do |format|
      if @lesson.update_attributes(params[:lesson])
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.destroy

    respond_to do |format|
      format.html { redirect_to lessons_url }
      format.json { head :ok }
    end
  end
end

app/helpers/lessons_helper.rb
module LessonsHelper
  include ApplicationHelper
end

app/views/lessons/_form.html.slim
= form_for @lesson do |f|
  -if @lesson.errors.any?
    #error_explanation
      h2 = "#{pluralize(@lesson.errors.count, "error")} prohibited this lesson from being saved:"
      ul
        - @lesson.errors.full_messages.each do |msg|
          li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :points
    = f.number_field :points
  .field
    = f.label :language_id
    = f.select 'language_id', options_from_collection_for_select(Language.all, "id", "name")
  .actions
    = f.submit 'Save', class: "ui-button ui-widget"

app/views/lessons/edit.html.slim
h1 Editing lesson

== render 'form'

= link_to 'Show', @lesson
'|
= link_to 'Back', lessons_path

app/views/lessons/index.html.slim
h1 Listing lessons

table.list-table
  tr
    th.ui-corner-tl Title
    th Description
    th Points
    th Language
    -if controller.logged_in_as_admin?
      th
      th
      th.ui-corner-tr
    -else
      th.ui-corner-tr

  - @lessons.each do |lesson|
    tr
      td= lesson.title
      td= lesson.description
      td= lesson.points
      td= link_to lesson.language.name, language_path(lesson.language)
      -if controller.logged_in_as_admin?
        td= link_to 'Show', lesson
        td= link_to 'Edit', edit_lesson_path(lesson)
        td= link_to 'Destroy', lesson, :confirm => 'Are you sure?', :method => :delete
      -else
        td= link_to 'Take', "/lessons/take/#{lesson.id}"

br

button.ui-button.ui-widget
  = link_to 'New Lesson', new_lesson_path, class: "ui-button-text-only"

app/views/lessons/new.html.slim
h1 New lesson

== render 'form'

button.ui-button.ui-widget
  = link_to 'Back', lessons_path, class: "ui-button-text-only"

app/views/lessons/show.html.slim
p#notice = notice

p
  b Title:
  = @lesson.title
p
  b Description:
  = @lesson.description
p
  b Points:
  = @lesson.points
p
  b Language:
  = link_to @lesson.language.name, language_path(@lesson.language)

p
  b Components:
  -for component in  @lesson.components
    -if component.is_a? Paragraph
      p
        b Paragraph:
        = component.body
    -else
      p 
        b Task:
        = component.input

= link_to 'Edit', edit_lesson_path(@lesson)
'|
= link_to 'Back', lessons_path

app/views/lessons/take.html.slim
#title
  span Language: 
  b = @lesson.title
  ' 
  = "Points: #{@lesson.points}"
  
-for component in @lesson.components
  -if component.is_a? Paragraph
    div.paragraph-container
      p.lesson-paragraph =component.body
  -else #then it's a task
    div.task-container[data-id="#{component.id}"]
      = text_area_tag "code_for_#{component.id}", component.initial_code, :class => "code-text-area"
      p.failure_feedback.none
      p.hint
      p.success_feedback.none Great job!
      button.submit-code.ui-button.ui-widget
        a.ui-button-text-only[href="/language/compile"] GO!

-if controller.logged_in?
  button#claim-points.ui-button.ui-widget
    a.ui-button-text-only[href="/users/#{session[:user_id]}/give_points/#{@lesson.id}"] Claim your points