config/routes.rb
Shaolin::Application.routes.draw do

  post "users/:user_id/give_points/:lesson_id" => "users#give_points"

  get "execution/execute"

  get "execution/match"
  match "lessons/take/:id" => "lessons#take"

  resources :sessions
  resources :users
  resources :lessons
  resources :paragraphs
  resources :tasks

  resources :languages
  match "language/compile" => "execution#execute"

  

  
  root :to => 'home#index'

end

app/models/paragraph.rb
class Paragraph < ActiveRecord::Base
  belongs_to :lesson
end

app/controllers/paragraphs_controller.rb
class ParagraphsController < ApplicationController
  # GET /paragraphs
  # GET /paragraphs.json
  def index
    @paragraphs = Paragraph.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @paragraphs }
    end
  end

  # GET /paragraphs/1
  # GET /paragraphs/1.json
  def show
    @paragraph = Paragraph.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @paragraph }
    end
  end

  # GET /paragraphs/new
  # GET /paragraphs/new.json
  def new
    @paragraph = Paragraph.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @paragraph }
    end
  end

  # GET /paragraphs/1/edit
  def edit
    @paragraph = Paragraph.find(params[:id])
  end

  # POST /paragraphs
  # POST /paragraphs.json
  def create
    @paragraph = Paragraph.new(params[:paragraph])

    respond_to do |format|
      if @paragraph.save
        format.html { redirect_to @paragraph, notice: 'Paragraph was successfully created.' }
        format.json { render json: @paragraph, status: :created, location: @paragraph }
      else
        format.html { render action: "new" }
        format.json { render json: @paragraph.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /paragraphs/1
  # PUT /paragraphs/1.json
  def update
    @paragraph = Paragraph.find(params[:id])

    respond_to do |format|
      if @paragraph.update_attributes(params[:paragraph])
        format.html { redirect_to @paragraph, notice: 'Paragraph was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @paragraph.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paragraphs/1
  # DELETE /paragraphs/1.json
  def destroy
    @paragraph = Paragraph.find(params[:id])
    @paragraph.destroy

    respond_to do |format|
      format.html { redirect_to paragraphs_url }
      format.json { head :ok }
    end
  end
end

app/helpers/paragraphs_helper.rb
module ParagraphsHelper
end

app/views/paragraphs/_form.html.slim
= form_for @paragraph do |f|
  -if @paragraph.errors.any?
    #error_explanation
      h2 = "#{pluralize(@paragraph.errors.count, "error")} prohibited this paragraph from being saved:"
      ul
        - @paragraph.errors.full_messages.each do |msg|
          li= msg

  .field
    = f.label :body
    = f.text_field :body
  .field
    = f.label :position
    = f.number_field :position
  .field
    = f.label :lesson_id
    = f.select 'lesson_id', options_from_collection_for_select(Lesson.all, "id", "title")
  .actions
    = f.submit 'Save', class: "ui-button ui-widget"

app/views/paragraphs/edit.html.slim
h1 Editing paragraph

== render 'form'

= link_to 'Show', @paragraph
'|
= link_to 'Back', paragraphs_path

app/views/paragraphs/index.html.slim
h1 Listing paragraphs

table.list-table
  tr
    th.ui-corner-tl Body
    th Lesson
    th Position
    th
    th
    th.ui-corner-tr

  - @paragraphs.each do |paragraph|
    tr
      td= paragraph.body
      td= link_to paragraph.lesson.title, lesson_path(paragraph.lesson)
      td= paragraph.position
      td= link_to 'Show', paragraph
      td= link_to 'Edit', edit_paragraph_path(paragraph)
      td= link_to 'Destroy', paragraph, :confirm => 'Are you sure?', :method => :delete

br

button.ui-button.ui-widget
  = link_to 'New Paragraph', new_paragraph_path, class: "ui-button-text-only"

app/views/paragraphs/new.html.slim
h1 New paragraph

== render 'form'

button.ui-button.ui-widget
  = link_to 'Back', paragraphs_path, class: "ui-button-text-only"

app/views/paragraphs/show.html.slim
p#notice = notice

p
  b Body:
  = @paragraph.body
p
  b Position:
  = @paragraph.position
p
  b Lesson:
  = link_to @paragraph.lesson.title, lesson_path(@paragraph.lesson)

= link_to 'Edit', edit_paragraph_path(@paragraph)
'|
= link_to 'Back', paragraphs_path